### ISSUE TITLE
movelist in tt

### ISSUE THREAD

**Issue by Disservin** [SirBob01/Brainiac#1]
`Add MoveList to transposition table hash to prevent recomputing legal moves`
This is more or less a bad idea. You dont want each entry of your transposition table to be huge. The smaller the entry (in bytes) the more positional information you can save. Saving the movelist would make each entry really big and you would have way less entries overall with the same TT size. Also because of the adjusted bounds you get a much smaller search tree so you are already saving a lot.

**Comment by SirBob01** [comment]
Thanks for the input! 

Yeah, I wasn't seriously considering that yet, it was just an idea that I was gonna investigate when I got to it. Do you think it's feasible to create a seprate move list table to avoid regenerating of moves? My profiler is telling me that it's dominating my search times.

**Comment by Disservin** [comment]
Well im looking at your move generation code right now and I have some optimizations. 1. Bishops cant move if they are pinned horizontally so you can skip the piece if it is pinned horizontal. Also I would really rewrite the movegen code into something smaller if i were you, its a bit more easier to look at the code, also queen moves are then just legal_rook_moves | legal_bishop_moves

        while (knights_mask) {
            Square from = poplsb(knights_mask);
            U64 moves = LegalKnightMoves(sideToMove, from);
            while (moves) {
                Square to = poplsb(moves);
                MoveFlag type = pieceAt(to);
                state._moves.add(from, to, type );
            }
        }

poplsb here returns the index and resets it, the fastest way to clear the lsb is simply `mask &= mask - 1`
capture or quiet is simply is there a piece at the square we move to ? 0 if it is empty and otherwise it returns the piece (which is > 0 thus true so 1)
I think you are also using vectors to store the moves right ? Simply use a movelist struct for this that has an movelist array[256]
most engines do this and the legal moves shouldnt be larger than 256 unless its some artificial position.
Also when generating the pinmask you dont need a seperate case for queen, since the union of rook and bishop is the queen mask.
So you simply make the king (the side that wants to move) a bishop (in theory) and then calculate the bishop attackmask that goes through your pieces and only stop until it reaches the first enemy, if that enemy is a bishop or a queen it might be a pin so then you check if theres only one piece between your king and this enemy piece, if so its a pin.
SQUARES_BETWEEN_BB is simply a bitmap of the squares between square 1 and square 2 if they are aligned horizontal/vertical or diagonal

    U64 bishop_mask = (Bishops(~c) | Queens(~c)) & BishopAttacks(sq, them);
    while (bishop_mask) {
        Square index = poplsb(bishop_mask);
        U64 possible_pin = (SQUARES_BETWEEN_BB[sq][index] | (1ULL << index));
        if (popcount(possible_pin & Us(c)) == 1)
            pinD |= possible_pin;
    }
you do the same for the rook

If you got any more questions you can message me on discord (linked on my profile) or just ask here
